# Generated by Django 5.2.16 on 2026-08-14 15:19

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_position_seconds', models.FloatField(default=0)),
                ('valid_stream_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=core.models.default_playback_expires_at)),
                ('unavailable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerQueue',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player_queue', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('track_ids', models.JSONField(blank=True, default=list)),
                ('current_index', models.IntegerField(default=-1)),
                ('repeat_mode', models.CharField(default='off', max_length=8)),
                ('shuffle_enabled', models.BooleanField(default=False)),
                ('volume', models.FloatField(default=0.75, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_type', models.CharField(choices=[('album', 'Album'), ('single', 'Single')], max_length=12)),
                ('title', models.CharField(max_length=180)),
                ('cover_original', models.ImageField(blank=True, null=True, upload_to='covers/originals/')),
                ('cover_512', models.ImageField(blank=True, null=True, upload_to='covers/512/')),
                ('cover_128', models.ImageField(blank=True, null=True, upload_to='covers/128/')),
                ('cover_url_external', models.CharField(blank=True, max_length=500, null=True)),
                ('genre', models.CharField(blank=True, max_length=80)),
                ('public_release_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('early_access_starts_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('archived_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreamEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_day', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('original_audio', models.FileField(blank=True, null=True, upload_to='audio/originals/')),
                ('processed_audio', models.FileField(blank=True, null=True, upload_to='audio/processed/')),
                ('audio_url_external', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('is_explicit', models.BooleanField(default=False)),
                ('processing_state', models.CharField(default='ready', max_length=16)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('unique_listener_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrackArtistCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('featured', 'Featured'), ('producer', 'Producer')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
