# Generated by Django 5.2.16 on 2026-08-14 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playbacksession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to='rooms.listeningroom'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recentlyplayed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_releases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='playback_session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_event', to='catalog.playbacksession'),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='track',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.release'),
        ),
        migrations.AddField(
            model_name='streamevent',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_events', to='catalog.track'),
        ),
        migrations.AddField(
            model_name='recentlyplayed',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.track'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to='catalog.track'),
        ),
        migrations.AddField(
            model_name='like',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='catalog.track'),
        ),
        migrations.AddField(
            model_name='trackartistcredit',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='track_credits', to='accounts.artistprofile'),
        ),
        migrations.AddField(
            model_name='trackartistcredit',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='catalog.track'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['user', 'local_day'], name='catalog_str_user_id_873fea_idx'),
        ),
        migrations.AddIndex(
            model_name='streamevent',
            index=models.Index(fields=['track', 'user'], name='catalog_str_track_i_9921e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'track')},
        ),
    ]
