from __future__ import annotations

from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from . import views

urlpatterns = [
    path("auth/register/", views.RegisterView.as_view(), name="register"),
    path("auth/register/artist/", views.RegisterView.as_view(), {"artist": True}, name="register-artist"),
    path("auth/login/", views.LoginView.as_view(), name="login"),
    path("auth/logout/", views.LogoutView.as_view(), name="logout"),
    path("auth/token/refresh/", views.RefreshView.as_view(), name="token-refresh"),
    path("auth/jwt/refresh/", TokenRefreshView.as_view(), name="jwt-refresh"),
    path("auth/password-reset/request/", views.PasswordResetRequestView.as_view(), name="password-reset-request"),
    path("auth/password-reset/confirm/", views.PasswordResetConfirmView.as_view(), name="password-reset-confirm"),
    path("me/", views.MeView.as_view(), name="me"),
    path("me/delete/", views.DeleteMeView.as_view(), name="me-delete"),
    path("me/library/", views.LibraryView.as_view(), name="library"),
    path("profiles/<str:username>/", views.ProfileView.as_view(), name="profile"),
    path("profiles/<str:username>/follow/", views.FollowView.as_view(), name="profile-follow"),
    path("artists/<str:username>/", views.ProfileView.as_view(), name="artist-profile"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("releases/", views.ReleaseListView.as_view(), name="releases"),
    path("releases/<uuid:pk>/", views.ReleaseDetailView.as_view(), name="release-detail"),
    path("tracks/", views.TrackListView.as_view(), name="tracks"),
    path("tracks/<uuid:pk>/", views.TrackDetailView.as_view(), name="track-detail"),
    path("tracks/<uuid:pk>/like/", views.LikeView.as_view(), name="track-like"),
    path("tracks/<uuid:pk>/playback-sessions/", views.PlaybackSessionView.as_view(), name="playback-session"),
    path("tracks/<uuid:pk>/download-tickets/", views.DownloadTicketView.as_view(), name="download-ticket"),
    path("playback-sessions/<uuid:pk>/progress/", views.PlaybackProgressView.as_view(), name="playback-progress"),
    path("media/streams/<path:token>/", views.StreamMediaView.as_view(), name="stream-media"),
    path("media/downloads/<path:token>/", views.StreamMediaView.as_view(), {"download": True}, name="download-media"),
    path("playlists/", views.PlaylistListView.as_view(), name="playlists"),
    path("playlists/<uuid:pk>/", views.PlaylistDetailView.as_view(), name="playlist-detail"),
    path("playlists/<uuid:pk>/tracks/", views.PlaylistTrackView.as_view(), name="playlist-tracks"),
    path("playlists/<uuid:pk>/tracks/<uuid:track_id>/", views.PlaylistTrackView.as_view(), name="playlist-track-detail"),
    path("playlists/<uuid:pk>/save/", views.PlaylistSaveView.as_view(), name="playlist-save"),
    path("playlists/<uuid:pk>/playback-context/", views.PlaybackContextView.as_view(), name="playlist-context"),
    path("artist/verification-requests/", views.ArtistVerificationView.as_view(), name="artist-verification"),
    path("artist/releases/", views.ArtistReleasesView.as_view(), name="artist-releases"),
    path("artist/releases/<uuid:pk>/", views.ArtistReleaseDetailView.as_view(), name="artist-release-detail"),
    path("artist/releases/<uuid:pk>/tracks/", views.ArtistTrackUploadView.as_view(), name="artist-track-upload"),
    path("artist/analytics/", views.ArtistAnalyticsView.as_view(), name="artist-analytics"),
    path("artist/payouts/", views.ArtistPayoutsView.as_view(), name="artist-payouts"),
    path("subscription/plans/", views.PlansView.as_view(), name="plans"),
    path("subscription/", views.SubscriptionView.as_view(), name="subscription"),
    path("subscription/purchases/", views.PurchaseView.as_view(), name="purchase"),
    path("payments/", views.PaymentsView.as_view(), name="payments"),
    path("payments/<str:provider>/callback/", views.PaymentCallbackView.as_view(), name="payment-callback"),
    path("notifications/", views.NotificationsView.as_view(), name="notifications"),
    path("notifications/mark-all-read/", views.NotificationReadView.as_view(), name="notifications-read-all"),
    path("notifications/<uuid:pk>/read/", views.NotificationReadView.as_view(), name="notification-read"),
    path("notifications/<uuid:pk>/", views.NotificationReadView.as_view(), name="notification-delete"),
    path("tickets/", views.TicketsView.as_view(), name="tickets"),
    path("tickets/<uuid:pk>/", views.TicketDetailView.as_view(), name="ticket-detail"),
    path("tickets/<uuid:pk>/messages/", views.TicketMessageView.as_view(), name="ticket-messages"),
    path("tickets/<uuid:pk>/claim/", views.TicketClaimView.as_view(), name="ticket-claim"),
    path("tickets/<uuid:pk>/close/", views.TicketCloseView.as_view(), name="ticket-close"),
    path("support/verification-requests/", views.SupportVerificationView.as_view(), name="support-verification"),
    path("support/verification-requests/<uuid:pk>/approve/", views.VerificationDecisionView.as_view(), {"approved": True}, name="verification-approve"),
    path("support/verification-requests/<uuid:pk>/reject/", views.VerificationDecisionView.as_view(), {"approved": False}, name="verification-reject"),
    path("admin/subscription-plans/", views.AdminPlansView.as_view(), name="admin-plans"),
    path("admin/audit-events/", views.AdminAuditView.as_view(), name="admin-audit"),
    path("admin/reports/overview/", views.AdminReportsView.as_view(), name="admin-reports"),
    path("admin/payouts/", views.AdminPayoutsView.as_view(), name="admin-payouts"),
    path("admin/payouts/<uuid:pk>/settle/", views.PayoutSettleView.as_view(), name="payout-settle"),
    path("admin/releases/<uuid:pk>/archive/", views.ArchiveReleaseView.as_view(), name="release-archive"),
    path("rooms/", views.RoomsView.as_view(), name="rooms"),
    path("rooms/<str:invite_code>/join/", views.RoomJoinView.as_view(), name="room-join"),
    path("rooms/<str:invite_code>/", views.RoomDetailView.as_view(), name="room-detail"),
    path("rooms/<uuid:pk>/leave/", views.RoomLeaveView.as_view(), name="room-leave"),
    path("rooms/<uuid:pk>/transfer-host/", views.RoomTransferHostView.as_view(), name="room-transfer-host"),
    path("rooms/<uuid:pk>/participants/<uuid:user_id>/permissions/", views.RoomPermissionsView.as_view(), name="room-permissions"),
    path("rooms/<uuid:pk>/queue/", views.RoomQueueView.as_view(), name="room-queue"),
]
